name: Shipwrecker
version: '1.0.0-SNAPSHOT'
main: net.donnypz.shipwrecker.Shipwrecker
api-version: '1.21'
depend:
  - MCCore
  - NoteBlockAPI
  - DisplayEntityUtils
  - DecentHolograms
commands:
  startmatch:
    description:
  endmatch:
    description:
  shop:
    description:
  addgold:
    description:
  addcoins:
    description:
  shipspeed:
    description:
  addfakematch:
    description:
  addfakeplayers:
    description:
  updatelb:
    description:

