name: Shipwrecker
version: '1.0.0-SNAPSHOT'
main: net.donnypz.shipwrecker.Shipwrecker
api-version: '1.21'
commands:
  startgame:
    description:
  addmarker:
    description:
  shop:
    description:
  addgold:
    description:
  addcoins:
    description:
  shipspeed:
    description:
  addfakematch:
    description:
